---
- name: Installing Tomcat Server
  hosts: all
  become: true

- tasks:
  - name: Install java
    yum:
      name: java
      state: latest

  - name: Download Tomcat package
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat- 10.0.4.tar.gz
      dest: /usr/local

  - name: Extract package
    unarchive:
      src: /usr/local/apache-tomcat- 10.0.4.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat- 10.0.4.tar.gz/bin/startup.sh