---
- name: Installing LAMP stack (Linux-Apache-MySQL-PHP)
  hosts: test servers
  become: true
  
  tasks:
  - name: Install Apache2
    package:
      name: "{{ item }}"
      state: present
    loop:
      - Apache2
      - libapache2-mod-php
      - php-cli
      - php-gd
      - php.mysql
      - mysql-server

  