---
- name: Installing Tomcat Server
  hosts: all
  become: true
  vars_files:
    - Tomcat_Variables.yml

  tasks:
  - name: Install java
    yum:
      name: java
      state: latest

  - name: Download Tomcat package
    get_url:
      url: "{{ tomcat_url }}"
      dest: /usr/local

  - name: Extract package
    unarchive:
      src: /usr/local/{{ tomcat_package }}
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh
