---
- name: Install and start nginx
  hosts: all
  become: true

  tasks:
#Installing nginx
  - name: Install nginx
    yum:
      name: nginx
      state: latest
      
#Starting nginx
  - name: Starting nginx
    service:
      name: nginx
      state: started