---
# tasks file for LAMPstack

  - name: install LAMPstack
    package:
      name: "{{ item }}"
      state: present
    loop:
        - apache2
        - libapache2-mod-php
        - php-cli
        - php-gd
        - php-mysql
        - mysql-server
