---
# tasks file for LAMPstack

  - name: Install Apache2
    package:
      name: "{{ item }}"
      state: present
      loop:
        - Apache2
        - libapache2-mod-php
        - php-cli
        - php-gd
        - php.mysql
        - mysql-server
